# Ecuaciones Diferenciales Parciales II - Práctica 1

## Alejandro Felipe Aviles - 6MV1  
Aproximar las primeras derivadas de las siguientes funciones empleando diferencias dinitas hacia adelante, hacia atrás, centradas. Calcule el error absoluto de la aproximación. Considere $h=0.1, 0.01, 0.001, 0.0001, 0.00001, 0.000001$.  
1. $f(x)=\dfrac{x}{\sqrt{x^2+9}},\,x=3$
2. $f(x)=\dfrac{x^3}{x^2+1},\,x=2$
3. $f(x)=\ln{(\cos{(x)+\sin{(x)}})},\,x=\dfrac{\pi}{2}$
4. $f(x)=e^{x}\cos{(x)},\,x=\pi$

**1)**

In [7]:
import numpy as np

# Definir la función y su derivada exacta
def f(x):
    return x / np.sqrt(x**2 + 9)

def df_exact(x):
    return 9 / (x**2 + 9)**(3/2)

# Punto donde se quiere calcular la derivada
x0 = 3

# Valores de paso
h = np.array([0.1, 0.01, 0.001,0.0001,0.00001,0.000001])

# Diferencias finitas hacia adelante
df_forward = (f(x0 + h) - f(x0)) / h
error_forward = np.abs(df_forward - df_exact(x0))

# Diferencias finitas hacia atrás
df_backward = (f(x0) - f(x0 - h)) / h
error_backward = np.abs(df_backward - df_exact(x0))

# Diferencias finitas centradas
df_centered = (f(x0 + h) - f(x0 - h)) / (2*h)
error_centered = np.abs(df_centered - df_exact(x0))

# Resultados
print("Derivada exacta:\n",df_exact(x0))
print("Diferencias finitas hacia adelante:")
print(df_forward)
print("Error absoluto para diferencias finitas hacia adelante:")
print(error_forward)
print("Diferencias finitas hacia atrás:")
print(df_backward)
print("Error absoluto para diferencias finitas hacia atrás:")
print(error_backward)
print("Diferencias finitas centradas:")
print(df_centered)
print("Error absoluto para diferencias finitas centradas:")
print(error_centered)


Derivada exacta: %f
 0.1178511301977579
Diferencias finitas hacia adelante:
[0.11495361 0.11755699 0.11782167 0.11784818 0.11785084 0.1178511 ]
Error absoluto para diferencias finitas hacia adelante:
[2.89752440e-03 2.94137121e-04 2.94578724e-05 2.94622966e-06
 2.94618511e-07 2.95416612e-08]
Diferencias finitas hacia atrás:
[0.12084684 0.11814625 0.1178806  0.11785408 0.11785142 0.11785116]
Error absoluto para diferencias finitas hacia atrás:
[2.99571319e-03 2.95119212e-04 2.94676934e-05 2.94632900e-06
 2.94632360e-07 2.96332260e-08]
Diferencias finitas centradas:
[0.11790022 0.11785162 0.11785114 0.11785113 0.11785113 0.11785113]
Error absoluto para diferencias finitas centradas:
[4.90943978e-05 4.91045351e-07 4.91050216e-09 4.96682001e-11
 6.92459978e-12 4.57824195e-11]


**2)**

In [1]:
import numpy as np

# Definir la función y su derivada exacta
def f(x):
    return x**3/(x**2+1)

def df_exact(x):
    return (x**4+3*x**2)/(x**4+2*x**2+1)

# Punto donde se quiere calcular la derivada
x0 = 2

# Valores de paso
h = np.array([0.1, 0.01, 0.001,0.0001,0.00001,0.000001])

# Diferencias finitas hacia adelante
df_forward = (f(x0 + h) - f(x0)) / h
error_forward = np.abs(df_forward - df_exact(x0))

# Diferencias finitas hacia atrás
df_backward = (f(x0) - f(x0 - h)) / h
error_backward = np.abs(df_backward - df_exact(x0))

# Diferencias finitas centradas
df_centered = (f(x0 + h) - f(x0 - h)) / (2*h)
error_centered = np.abs(df_centered - df_exact(x0))

# Resultados
print("Derivada exacta:\n",df_exact(x0))
print("Diferencias finitas hacia adelante:")
print(df_forward)
print("Error absoluto para diferencias finitas hacia adelante:")
print(error_forward)
print("Diferencias finitas hacia atrás:")
print(df_backward)
print("Error absoluto para diferencias finitas hacia atrás:")
print(error_backward)
print("Diferencias finitas centradas:")
print(df_centered)
print("Error absoluto para diferencias finitas centradas:")
print(error_centered)


Derivada exacta: %f
 1.12
Diferencias finitas hacia adelante:
[1.11829945 1.11983889 1.11998399 1.1199984  1.11999984 1.11999998]
Error absoluto para diferencias finitas hacia adelante:
[1.70055453e-03 1.61107915e-04 1.60111884e-05 1.60011003e-06
 1.59995341e-07 1.59105964e-08]
Diferencias finitas hacia atrás:
[1.12147505 1.12015887 1.12001599 1.1200016  1.12000016 1.12000002]
Error absoluto para diferencias finitas hacia atrás:
[1.47505423e-03 1.58867765e-04 1.59887879e-05 1.59988801e-06
 1.60015344e-07 1.60638267e-08]
Diferencias finitas centradas:
[1.11988725 1.11999888 1.11999999 1.12       1.12       1.12      ]
Error absoluto para diferencias finitas centradas:
[1.12750149e-04 1.12007488e-06 1.12002532e-08 1.11012532e-10
 1.00017772e-11 7.66151587e-11]


**3)**

In [3]:
import numpy as np

# Definir la función y su derivada exacta
def f(x):
    return np.log(np.cos(x)+np.sin(x))

def df_exact(x):
    return (np.cos(x)-np.sin(x))/(np.sin(x)+np.cos(x))

# Punto donde se quiere calcular la derivada
x0 = np.pi/2

# Valores de paso
h = np.array([0.1, 0.01, 0.001,0.0001,0.00001,0.000001])

# Diferencias finitas hacia adelante
df_forward = (f(x0 + h) - f(x0)) / h
error_forward = np.abs(df_forward - df_exact(x0))

# Diferencias finitas hacia atrás
df_backward = (f(x0) - f(x0 - h)) / h
error_backward = np.abs(df_backward - df_exact(x0))

# Diferencias finitas centradas
df_centered = (f(x0 + h) - f(x0 - h)) / (2*h)
error_centered = np.abs(df_centered - df_exact(x0))

# Resultados
print("Derivada exacta: \n",df_exact(x0))
print("Diferencias finitas hacia adelante:")
print(df_forward)
print("Error absoluto para diferencias finitas hacia adelante:")
print(error_forward)
print("Diferencias finitas hacia atrás:")
print(df_backward)
print("Error absoluto para diferencias finitas hacia atrás:")
print(error_backward)
print("Diferencias finitas centradas:")
print(df_centered)
print("Error absoluto para diferencias finitas centradas:")
print(error_centered)


Derivada exacta: %f
 -0.9999999999999999
Diferencias finitas hacia adelante:
[-1.10740798 -1.01006734 -1.00100067 -1.00010001 -1.00001    -1.000001  ]
Error absoluto para diferencias finitas hacia adelante:
[1.07407983e-01 1.00673401e-02 1.00066733e-03 1.00006666e-04
 1.00000681e-05 9.99851995e-07]
Diferencias finitas hacia atrás:
[-0.90606025 -0.99006601 -0.99900067 -0.99990001 -0.99999    -0.999999  ]
Error absoluto para diferencias finitas hacia atrás:
[9.39397474e-02 9.93399340e-03 9.99333999e-04 9.99933325e-05
 9.99991053e-06 1.00012588e-06]
Diferencias finitas centradas:
[-1.00673412 -1.00006667 -1.00000067 -1.00000001 -1.         -1.        ]
Error absoluto para diferencias finitas centradas:
[6.73411784e-03 6.66733341e-05 6.66667201e-07 6.66677835e-09
 7.87822030e-11 1.36944345e-10]


**4)**

In [5]:
import numpy as np

# Definir la función y su derivada exacta
def f(x):
    return np.exp(x)*np.cos(x)

def df_exact(x):
    return np.exp(x)*np.cos(x)-np.exp(x)*np.sin(x)

# Punto donde se quiere calcular la derivada
x0 = np.pi

# Valores de paso
h = np.array([0.1, 0.01, 0.001,0.0001,0.00001,0.000001])

# Diferencias finitas hacia adelante
df_forward = (f(x0 + h) - f(x0)) / h
error_forward = np.abs(df_forward - df_exact(x0))

# Diferencias finitas hacia atrás
df_backward = (f(x0) - f(x0 - h)) / h
error_backward = np.abs(df_backward - df_exact(x0))

# Diferencias finitas centradas
df_centered = (f(x0 + h) - f(x0 - h)) / (2*h)
error_centered = np.abs(df_centered - df_exact(x0))

# Resultados
print("Derivada exacta: \n",df_exact(x0))
print("Diferencias finitas hacia adelante:")
print(df_forward)
print("Error absoluto para diferencias finitas hacia adelante:")
print(error_forward)
print("Diferencias finitas hacia atrás:")
print(df_backward)
print("Error absoluto para diferencias finitas hacia atrás:")
print(error_backward)
print("Diferencias finitas centradas:")
print(df_centered)
print("Error absoluto para diferencias finitas centradas:")
print(error_centered)


Derivada exacta: 
 -23.14069263277927
Diferencias finitas hacia adelante:
[-23.05962311 -23.13991741 -23.14068492 -23.14069256 -23.14069263
 -23.14069263]
Error absoluto para diferencias finitas hacia adelante:
[8.10695222e-02 7.75220917e-04 7.71742490e-06 7.70938655e-08
 9.94742066e-10 4.26346958e-10]
Diferencias finitas hacia atrás:
[-23.06733667 -23.13992513 -23.14068492 -23.14069256 -23.14069263
 -23.14069264]
Error absoluto para diferencias finitas hacia atrás:
[7.33559598e-02 7.67507353e-04 7.70970841e-06 7.70583384e-08
 6.39470699e-10 3.97906064e-09]
Diferencias finitas centradas:
[-23.06347989 -23.13992127 -23.14068492 -23.14069256 -23.14069263
 -23.14069263]
Error absoluto para diferencias finitas centradas:
[7.72127410e-02 7.71364135e-04 7.71356665e-06 7.70761019e-08
 8.17106383e-10 2.20270380e-09]
